#!/usr/bin/env node
// build.mjs — Vercel build step for the Interlock safety panel.
//
// A pure-static page cannot read Vercel env vars (they exist only at build /
// server runtime), so the build bakes them into the output as dist/config.js,
// which the panel imports. No npm dependencies — plain node:fs/path.
//
// Vercel project settings (for this repo):
//   Root Directory    : frontend
//   Framework Preset  : Other
//   Build Command     : node build.mjs
//   Output Directory  : dist
//   Environment Vars  : INTERLOCK_ADDRESS, VAULT_ADDRESS   (0x + 40 hex each)
//
// What it does:
//   1. copies the static site (index.html, style.css, *.js) into dist/
//   2. writes dist/config.js with the addresses resolved from the env vars
//      above, falling back to the committed defaults in ./config.js when an
//      env var is unset — so a bare build (or a preview with no vars) still
//      points at the deploy-card pair.
//   Addresses are passed through VERBATIM: studionet's registry is
//   case-sensitive, so copy the deployed address strings exactly as shown.
import { mkdirSync, copyFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { CONFIG as DEFAULTS } from "./config.js";

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, "dist");
const IS_ADDR = (s) => /^0x[0-9a-fA-F]{40}$/.test(String(s ?? "").trim());

function resolveVar(name, fallback) {
  const raw = (process.env[name] ?? "").trim();
  if (!raw) return fallback;
  if (!IS_ADDR(raw)) {
    console.error(`[build] ${name}="${raw}" is not a valid contract address (expect 0x + 40 hex).`);
    process.exit(1);
  }
  return raw; // verbatim — studionet resolves contracts by EXACT address string (case-sensitive)
}

const config = {
  interlock: resolveVar("INTERLOCK_ADDRESS", DEFAULTS.interlock),
  vault: resolveVar("VAULT_ADDRESS", DEFAULTS.vault),
};

// 1. copy the static site (skip the build artifact, tooling, and hidden files)
mkdirSync(dist, { recursive: true });
const skip = new Set(["dist", "node_modules", "tools", "build.mjs", "package.json", "package-lock.json"]);
for (const name of readdirSync(here)) {
  if (name.startsWith(".") || skip.has(name)) continue;
  const p = join(here, name);
  if (statSync(p).isFile()) copyFileSync(p, join(dist, name));
}

// 2. bake the resolved config into the output the panel actually imports
writeFileSync(
  join(dist, "config.js"),
  "// GENERATED by build.mjs — do not edit.\n" +
    "// Source: Vercel env vars INTERLOCK_ADDRESS / VAULT_ADDRESS,\n" +
    "// falling back to the committed defaults in frontend/config.js.\n" +
    `export const CONFIG = ${JSON.stringify(config, null, 2)};\n`,
);

console.log("[build] dist/ ready — panel will point at:");
console.log(`  interlock ${config.interlock}`);
console.log(`  vault     ${config.vault}`);
